<a href="https://colab.research.google.com/github/lhiwi/FUTURE_DS_03/blob/main/notebooks/%20data_understanding_and_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
## Import libraries

import pandas as pd
import numpy as np

In [ ]:
# Load the dataset
file_path = "/content/drive/MyDrive/Future_DS/FUTURE_DS_03/data/bank-full.csv"
df = pd.read_csv(file_path, sep=';')

In [ ]:
df.shape

(45211, 17)

In [ ]:
# Preview dataset
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [ ]:
df.columns.tolist()

['age',
 'job',
 'marital',
 'education',
 'default',
 'balance',
 'housing',
 'loan',
 'contact',
 'day',
 'month',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'y']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

In [ ]:
for col in df.select_dtypes(include='object').columns:
    unknown_count = (df[col] == 'unknown').sum()
    print(f"{col}: {unknown_count}")

job: 288
marital: 0
education: 1857
default: 0
housing: 0
loan: 0
contact: 13020
month: 0
poutcome: 36959
y: 0

In [ ]:
 ## Check for duplicate records
df.duplicated().sum()

np.int64(0)

## Check conversion outcome distribution

We examine the target variable `y` to understand how many customers converted and how many did not

In [ ]:
df['y'].value_counts()

y
no     39922
yes     5289
Name: count, dtype: int64

In [ ]:
df['y'].value_counts(normalize=True) * 100

y
no     88.30152
yes    11.69848
Name: proportion, dtype: float64

## Summary statistics for numerical variables

We analyze numerical columns to understand their distribution, detect extreme values, and identify any anomalies that may require cleaning or transformation.

In [ ]:
df.describe()

,age,balance,day,duration,campaign,pdays,previous
count,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000,45211.000000
mean,40.936210,1362.272058,15.806419,258.163080,2.763841,40.197828,0.580323
std,10.618762,3044.765829,8.322476,257.527812,3.098021,100.128746,2.303441
min,18.000000,-8019.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
25%,33.000000,72.000000,8.000000,103.000000,1.000000,-1.000000,0.000000
50%,39.000000,448.000000,16.000000,180.000000,2.000000,-1.000000,0.000000
75%,48.000000,1428.000000,21.000000,319.000000,3.000000,-1.000000,0.000000
max,95.000000,102127.000000,31.000000,4918.000000,63.000000,871.000000,275.000000

## Create a feature for previous contact

The `pdays` variable uses -1 to indicate that the customer was not contacted in a previous campaign.  
We create a new binary feature to make this easier to interpret in analysis.

In [ ]:
df['was_contacted_before'] = df['pdays'].apply(lambda x: 'no' if x == -1 else 'yes')

In [ ]:
df['was_contacted_before'].value_counts()

was_contacted_before
no     36954
yes     8257
Name: count, dtype: int64

## Create conversion flag

The target column `y` contains yes/no values. We create a numeric conversion flag where converted customers are coded as 1 and non-converted customers are coded as 0. This makes KPI calculations easier later.

In [ ]:
df['conversion_flag'] = df['y'].map({'yes': 1, 'no': 0})

In [ ]:
df[['y', 'conversion_flag']].head()

    y  conversion_flag
0  no                0
1  no                0
2  no                0
3  no                0
4  no                0

## Save cleaned dataset

We save the cleaned dataset to Google Drive so it can be reused for analysis and dashboard development without repeating the cleaning steps.

In [ ]:
output_path = "/content/drive/MyDrive/Future_DS/FUTURE_DS_03/data/bank_cleaned.csv"
df.to_csv(output_path, index=False)

In [ ]:
import os
os.path.exists(output_path)

True